project:
  type: website

website:
  title: "What Grad School Don’t Teach You: Tools for Transparent and Reproducible Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Slides/index.qmd
        text: Slides

format:
  html:
    theme:
      - yeti
      - tweaks.scss
    toc: true
brand: brand.yml



